### ISSUE TITLE
Unable to run Example Web with CosmosDb

### ISSUE THREAD

**Issue by pengo98** [jet/equinox#155]
`bash-3.2$ EQUINOX_COSMOS_CONNECTION="AccountEndpoint=https://xxx.xxx/;AccountKey=xxxxxx"
bash-3.2$ EQUINOX_COSMOS_DATABASE="equinox-test"
bash-3.2$ EQUINOX_COSMOS_CONTAINER="equinox-test"
bash-3.2$ dotnet run -p Web
Event Storage subsystem requires the following Environment Variables to be specified: EQUINOX_COSMOS_CONNECTION, EQUINOX_COSMOS_DATABASE, EQUINOX_COSMOS_COLLECTION `

**Comment by bartelink** [comment]
Thanks for trying; apologies that you're having problems. Hopefully the following helps (please close if they do)

for bash, I believe you want to do `export EQUINOX_COSMOS_CONNECTION="AccountEndpoint=https://xxx.xxx/;AccountKey=xxxxxx"` etc

`env` can be used to debug whether the env vars are being set

(alternately `brew install cask pwsh` and you can use the `$env:X="Y"` syntax, but that may be a big leap!)

**Comment by bartelink** [comment]
Closing for now. Please reopen if any further input is necessary

**Comment by precisemath** [comment]
The suggestion did not work for me. Here are my commands:
`
dotnet tool install Equinox.Tool -g
You can invoke the tool using the following command: eqx
Tool 'equinox.tool' (version '1.0.4') was successfully installed

export EQUINOX_COSMOS_CONNECTION="AccountEndpoint=https://xxx:443/;AccountKey=yyy;"
export EQUINOX_COSMOS_DATABASE="equinox-test"
export EQUINOX_COSMOS_CONTAINER="equinox-test"

dotnet new eqxweb -t -c
`
Here is the error message I am getting:
Event Storage subsystem requires the following Environment Variables to be specified: EQUINOX_COSMOS_CONNECTION, EQUINOX_COSMOS_DATABASE, EQUINOX_COSMOS_COLLECTION

To debug and check whether the environment variables were setup correctly, I ran the following commands:

`
env | grep EQUINOX
EQUINOX_COSMOS_CONNECTION=AccountEndpoint=https://xxx:443/;AccountKey=yyy;
EQUINOX_COSMOS_CONTAINER=equinox-test
EQUINOX_COSMOS_DATABASE=equinox-test

echo $SHELL
/bin/bash
`

**Comment by precisemath** [comment]
@bartelink  I am unable to reopen this issue as I did not open this issue so I am tagging you here to re-open this issue if possible on your end.

**Comment by bartelink** [comment]
@precisemath apologies - the fix in this instance is to `export EQUINOX_COSMOS_CONNECTION=$EQUINOX_COSMOS_CONTAINER`. Will explain shortly...

**Comment by bartelink** [comment]
Also, apologies to @pengo98 for not figuring it out from the first report - your cited messages should have been enough for me to figure out the issue. TL;DR the docs are talking about the new name - `EQUINOX_COSMOS_CONTAINER`, but the non-prerelease version of the tool (`1.0.4`) still uses the old name, `EQUINOX_COSMOS_COLLECTION`. Unfortunately I've removed the instructions from the README.md as to how to install the pre-release edition.

Why the rename? The v3 SDK and the Azure portal (essentially all stuff from MS going forward) refers to containers instead of collections, so I'm including this breaking change in the v2 release cycle. The environment variables are only used by the output of the templates and the `eqx` tool.

Missing bit from README:
```
    # TEMP: need to uninstall and use --version flag while this is in RC
    dotnet tool uninstall Equinox.Tool -g
    dotnet tool install Equinox.Tool -g --version 2.0.0-rc*
```

There's no problem with duplicating the env var as a workaround either, i.e its not critical to have the latest version of the tool as the schema is the same (main change in the tool is new feature to assign RUs at DB level, and moving some duties out to `Propulsion.Tool`).

Apologies again for the frustration :(

**Comment by bartelink** [comment]
README updated https://github.com/jet/equinox/commit/01f6cd2af7a78e0510bdf3302a007cdf1e15946c#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by bartelink** [comment]
Sorry, one final point: the [current release of the templates](https://github.com/jet/dotnet-templates/blob/master/CHANGELOG.md#3.1.0) still has code using `EQUINOX_COSMOS_COLLECTION`. Will post when it's released (next few days). You can work around by adjusting the env var.

**Comment by bartelink** [comment]
(It should also be noted that the container is expected to have been created before starting; the 1.x version of the tool will look for `EQUINOX_COSMOS_COLLECTION` but the newer version uses `EQUINOX_COSMOS_CONTAINER`, though the explicit parameter override `-c $MY_VAR` will work of course either way. I assume at least one of you were misled by the tool working but the app not. Again, my bad)
